import http.server
import socketserver
import threading

import pytest

from sentinel.core.models import (
    AssetCriticality,
    EnvironmentLabel,
    Policy,
    Scope,
    Target,
    TargetMetadata,
    TargetSet,
    TargetType,
    Task,
    TaskMode,
    TaskStatus,
)
from sentinel.core.orchestrator.orchestrator import orchestrator
from sentinel.intelligence.risk.finding_engine import finding_engine
from sentinel.intelligence.risk.risk_engine import risk_engine
from sentinel.storage.evidence.store import evidence_store


class MockTestServer(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(b"SENTINEL E2E TEST TARGET")


@pytest.fixture(scope="module")
def live_test_target():
    server = socketserver.TCPServer(("127.0.0.1", 18890), MockTestServer)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    yield "http://127.0.0.1:18890"
    server.shutdown()


@pytest.mark.asyncio
async def test_autonomous_orchestrator_e2e(live_test_target):
    # Setup target and scope for local test daemon
    target = Target(
        id="t-e2e-01",
        type=TargetType.URL,
        value="http://127.0.0.1:18890",
        metadata=TargetMetadata(
            criticality=AssetCriticality.HIGH,
            environment=EnvironmentLabel.STAGING,
            owner="secops",
        ),
    )
    target_set = TargetSet(id="ts-e2e", name="E2E Target Set", targets=[target])

    scope = Scope(
        id="scope-e2e",
        name="E2E Testing Scope",
        allowed_targets=["127.0.0.1", "http://127.0.0.1:18890", "127.0.0.1:18890"],
        max_intensity=5,
    )

    policy = Policy(
        id="pol-e2e",
        name="E2E Standard Policy",
        allowed_module_classes=["recon", "network"],
        allowed_action_classes=["*"],
    )

    task = Task(
        id="task-e2e-01",
        objective="Perform autonomous assessment of live local web service",
        target_set=target_set,
        scope=scope,
        policy=policy,
        mode=TaskMode.ASSESSMENT,
        correlation_id="corr-e2e-01",
    )

    # Run full autonomous loop
    completed_task = await orchestrator.run_task(task, max_iterations=5)

    assert completed_task.status == TaskStatus.COMPLETE
    assert completed_task.progress_percentage == 100.0
    assert completed_task.completed_at is not None

    # Verify Evidence was captured and stored
    task_evidence = evidence_store.query_evidence(task_id=task.id)
    assert len(task_evidence) > 0

    # Verify Findings were generated by ReconAgent
    task_findings = finding_engine.list_findings(task_id=task.id)
    assert len(task_findings) > 0

    # Verify Risk profile was dynamically calculated
    risk_summary = risk_engine.get_task_risk_summary(task.id, task_findings)
    assert risk_summary.total_findings > 0
    assert risk_summary.overall_risk_score > 0.0
