"""Sentinel Autonomous Planner Interface and Heuristic Planner.

Defines the LLM-agnostic Planner contract and implements the HeuristicPlanner:
a disciplined, phase-based planning engine following cybersecurity best practices.
"""

import uuid
from abc import ABC, abstractmethod
from urllib.parse import urlparse

from pydantic import BaseModel, Field

from sentinel.core.agents.base import AgentRegistry
from sentinel.core.memory.working_memory import TaskWorkingMemory
from sentinel.core.models import (
    ActionRequest,
    ImpactLevel,
    Task,
)


class PlannedStep(BaseModel):
    """An atomic planned execution step."""
    step_id: str = Field(default_factory=lambda: f"step-{uuid.uuid4().hex[:8]}")
    agent_name: str
    action_request: ActionRequest
    phase: str
    justification: str


class ExecutionPlan(BaseModel):
    """An ordered plan of execution steps generated by the Planner."""
    plan_id: str = Field(default_factory=lambda: f"plan-{uuid.uuid4().hex[:8]}")
    task_id: str
    reasoning_trace: list[str] = Field(default_factory=list)
    steps: list[PlannedStep] = Field(default_factory=list)
    is_terminal: bool = False
    confidence_is_sufficient: bool = False


class BasePlanner(ABC):
    """Abstract interface for all Autonomous Planners (Heuristic, LLM, Reinforcement)."""

    @abstractmethod
    async def generate_plan(
        self,
        task: Task,
        memory: TaskWorkingMemory,
        registry: AgentRegistry,
    ) -> ExecutionPlan:
        """Analyze task state and working memory to select the next optimal execution plan."""
        pass


class HeuristicPlanner(BasePlanner):
    """Rule-based, phase-driven deterministic cybersecurity planner."""

    async def generate_plan(
        self,
        task: Task,
        memory: TaskWorkingMemory,
        registry: AgentRegistry,
    ) -> ExecutionPlan:
        plan = ExecutionPlan(task_id=task.id)
        targets = task.target_set.targets

        if not targets:
            plan.is_terminal = True
            plan.confidence_is_sufficient = True
            plan.reasoning_trace.append("No targets provided in task context. Halting planning.")
            return plan

        # Phase 1: Baseline Reconnaissance (DNS + HTTP Observation)
        if "phase_recon_done" not in memory.state_flags:
            plan.reasoning_trace.append("Phase 1: Initializing baseline reconnaissance across target set.")
            for t in targets:
                # Extract clean hostname for network/dns checks
                val = t.value
                parsed = urlparse(val)
                hostname = parsed.hostname or val

                # 1. DNS Lookup for non-IP domain targets
                if t.type.value == "domain" and not all(c.isdigit() or c == "." for c in hostname):
                    req_dns = ActionRequest(
                        id=f"act-plan-dns-{uuid.uuid4().hex[:8]}",
                        task_id=task.id,
                        agent="recon_agent",
                        action_type="dns.lookup",
                        target_refs=[hostname],
                        parameters={"record_types": ["A", "AAAA", "MX", "NS", "TXT"]},
                        expected_impact_level=ImpactLevel.LOW,
                    )
                    plan.steps.append(
                        PlannedStep(
                            agent_name="recon_agent",
                            action_request=req_dns,
                            phase="RECONNAISSANCE",
                            justification=f"Enumerate DNS infrastructure and records for target asset '{hostname}'.",
                        )
                    )

                # 2. HTTP/TLS Observation
                req_http = ActionRequest(
                    id=f"act-plan-http-{uuid.uuid4().hex[:8]}",
                    task_id=task.id,
                    agent="recon_agent",
                    action_type="http.observe",
                    target_refs=[t.value],
                    parameters={},
                    expected_impact_level=ImpactLevel.LOW,
                )
                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=req_http,
                        phase="RECONNAISSANCE",
                        justification=f"Observe HTTP headers, TLS certificate, and redirect chains for '{t.value}'.",
                    )
                )

            memory.state_flags["phase_recon_done"] = True
            return plan

        # Phase 2: Service & Port Discovery
        if "phase_discovery_done" not in memory.state_flags:
            plan.reasoning_trace.append("Phase 2: Executing network service and port discovery.")
            for t in targets:
                parsed = urlparse(t.value)
                host_target = parsed.hostname or t.value
                port = parsed.port or (443 if parsed.scheme == "https" else 80)

                req_net = ActionRequest(
                    id=f"act-plan-net-{uuid.uuid4().hex[:8]}",
                    task_id=task.id,
                    agent="recon_agent",
                    action_type="network.service_scan",
                    target_refs=[host_target],
                    parameters={"ports": [port, 80, 443, 8080, 8443, 18890], "force_python_fallback": True},
                    expected_impact_level=ImpactLevel.LOW,
                )
                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=req_net,
                        phase="DISCOVERY",
                        justification=f"Scan TCP services on '{host_target}'.",
                    )
                )

            memory.state_flags["phase_discovery_done"] = True
            return plan

        # Terminal Phase: Assessment Finished
        plan.reasoning_trace.append("All engagement phases completed. Target assessment confidence is sufficient.")
        plan.is_terminal = True
        plan.confidence_is_sufficient = True
        return plan


# Global Default Planner Singleton
heuristic_planner = HeuristicPlanner()
