"""Sentinel Autonomous Planner Interface and Heuristic Planner.

Defines the LLM-agnostic Planner contract and implements the HeuristicPlanner:
a disciplined, phase-based planning engine following cybersecurity best practices.
"""

import uuid
from abc import ABC, abstractmethod
from urllib.parse import urlparse

from pydantic import BaseModel, Field

from sentinel.core.agents.base import AgentRegistry
from sentinel.core.memory.working_memory import TaskWorkingMemory
from sentinel.core.models import (
    ActionRequest,
    ImpactLevel,
    Task,
)


class PlannedStep(BaseModel):
    """An atomic planned execution step."""
    step_id: str = Field(default_factory=lambda: f"step-{uuid.uuid4().hex[:8]}")
    agent_name: str
    action_request: ActionRequest
    phase: str
    justification: str


class ExecutionPlan(BaseModel):
    """An ordered plan of execution steps generated by the Planner."""
    plan_id: str = Field(default_factory=lambda: f"plan-{uuid.uuid4().hex[:8]}")
    task_id: str
    reasoning_trace: list[str] = Field(default_factory=list)
    steps: list[PlannedStep] = Field(default_factory=list)
    is_terminal: bool = False
    confidence_is_sufficient: bool = False


class BasePlanner(ABC):
    """Abstract interface for all Autonomous Planners (Heuristic, LLM, Reinforcement)."""

    @abstractmethod
    async def generate_plan(
        self,
        task: Task,
        memory: TaskWorkingMemory,
        registry: AgentRegistry,
    ) -> ExecutionPlan:
        """Analyze task state and working memory to select the next optimal execution plan."""
        pass


class HeuristicPlanner(BasePlanner):
    """Rule-based, phase-driven deterministic cybersecurity planner."""

    async def generate_plan(
        self,
        task: Task,
        memory: TaskWorkingMemory,
        registry: AgentRegistry,
    ) -> ExecutionPlan:
        plan = ExecutionPlan(task_id=task.id)
        targets = task.target_set.targets

        if not targets:
            plan.is_terminal = True
            plan.confidence_is_sufficient = True
            plan.reasoning_trace.append("No targets provided in task context. Halting planning.")
            return plan

        # Phase 1: Baseline DNS & OSINT Intelligence
        if "phase_recon_baseline_done" not in memory.state_flags:
            plan.reasoning_trace.append("Phase 1: Gathering baseline DNS, Subdomain, OSINT, and IP intelligence.")
            for t in targets:
                val = t.value
                parsed = urlparse(val if "://" in val else f"http://{val}")
                hostname = parsed.hostname or val

                # 1. DNS Full Enumeration & Zone Info
                if not all(c.isdigit() or c == "." for c in hostname):
                    plan.steps.append(
                        PlannedStep(
                            agent_name="recon_agent",
                            action_request=ActionRequest(
                                id=f"act-plan-dns-{uuid.uuid4().hex[:8]}",
                                task_id=task.id,
                                agent="recon_agent",
                                action_type="dns.full_enum",
                                target_refs=[hostname],
                                expected_impact_level=ImpactLevel.LOW,
                            ),
                            phase="RECON_DNS",
                            justification=f"Enumerate complete DNS records and zone transfer capabilities for '{hostname}'.",
                        )
                    )
                    # Subdomain Enumeration
                    plan.steps.append(
                        PlannedStep(
                            agent_name="recon_agent",
                            action_request=ActionRequest(
                                id=f"act-plan-sub-{uuid.uuid4().hex[:8]}",
                                task_id=task.id,
                                agent="recon_agent",
                                action_type="recon.subdomains",
                                target_refs=[hostname],
                                expected_impact_level=ImpactLevel.LOW,
                            ),
                            phase="RECON_SUBDOMAINS",
                            justification=f"Discover subdomains via certificate transparency and wordlists for '{hostname}'.",
                        )
                    )

                # 2. IP & ASN Intelligence
                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=ActionRequest(
                            id=f"act-plan-ip-{uuid.uuid4().hex[:8]}",
                            task_id=task.id,
                            agent="recon_agent",
                            action_type="recon.ip_intel",
                            target_refs=[hostname],
                            expected_impact_level=ImpactLevel.LOW,
                        ),
                        phase="RECON_IP",
                        justification=f"Identify geolocation, ASN routing, and hosting provider for '{hostname}'.",
                    )
                )

                # 3. OSINT & Security.txt
                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=ActionRequest(
                            id=f"act-plan-osint-{uuid.uuid4().hex[:8]}",
                            task_id=task.id,
                            agent="recon_agent",
                            action_type="recon.osint",
                            target_refs=[val],
                            expected_impact_level=ImpactLevel.LOW,
                        ),
                        phase="RECON_OSINT",
                        justification=f"Audit security.txt contacts and robots.txt disclosures for '{val}'.",
                    )
                )

            memory.state_flags["phase_recon_baseline_done"] = True
            return plan

        # Phase 2: Web & Technology Fingerprinting
        if "phase_web_fingerprint_done" not in memory.state_flags:
            plan.reasoning_trace.append("Phase 2: Executing HTTP surface observation, TLS inspection, and tech fingerprinting.")
            for t in targets:
                val = t.value
                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=ActionRequest(
                            id=f"act-plan-http-{uuid.uuid4().hex[:8]}",
                            task_id=task.id,
                            agent="recon_agent",
                            action_type="http.observe",
                            target_refs=[val],
                            expected_impact_level=ImpactLevel.LOW,
                        ),
                        phase="WEB_OBSERVE",
                        justification=f"Observe HTTP status, security headers, and redirect chains on '{val}'.",
                    )
                )
                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=ActionRequest(
                            id=f"act-plan-tech-{uuid.uuid4().hex[:8]}",
                            task_id=task.id,
                            agent="recon_agent",
                            action_type="recon.tech_fingerprint",
                            target_refs=[val],
                            expected_impact_level=ImpactLevel.LOW,
                        ),
                        phase="WEB_FINGERPRINT",
                        justification=f"Fingerprint web technologies, frameworks, and cookies for '{val}'.",
                    )
                )

            memory.state_flags["phase_web_fingerprint_done"] = True
            return plan

        # Phase 3: Service & Port Discovery
        if "phase_discovery_done" not in memory.state_flags:
            plan.reasoning_trace.append("Phase 3: Executing network service and port discovery.")
            for t in targets:
                parsed = urlparse(t.value if "://" in t.value else f"http://{t.value}")
                host_target = parsed.hostname or t.value
                port = parsed.port or (443 if parsed.scheme == "https" else 80)

                plan.steps.append(
                    PlannedStep(
                        agent_name="recon_agent",
                        action_request=ActionRequest(
                            id=f"act-plan-net-{uuid.uuid4().hex[:8]}",
                            task_id=task.id,
                            agent="recon_agent",
                            action_type="network.service_scan",
                            target_refs=[host_target],
                            parameters={"ports": [port, 80, 443, 8080, 8443, 18890], "force_python_fallback": True},
                            expected_impact_level=ImpactLevel.LOW,
                        ),
                        phase="SERVICE_DISCOVERY",
                        justification=f"Scan TCP listening services on '{host_target}'.",
                    )
                )

            memory.state_flags["phase_discovery_done"] = True
            return plan

        # Terminal Phase: Assessment Finished
        plan.reasoning_trace.append("All reconnaissance and attack surface mapping phases completed.")
        plan.is_terminal = True
        plan.confidence_is_sufficient = True
        return plan


# Global Default Planner Singleton
heuristic_planner = HeuristicPlanner()
